site_name: memo marvel-app
repo_name: alex1dre-girard/marvel-app-memo

nav:
  - Version 1.0: version-1.0.md
  - Version 1.1: version-1.1.md

theme:
  name: material
  language: fr
  features:
    # Permet d'afficher le menu de navigation sous forme d'onglets
    - navigation.tabs
    # Permet de garder le menu de navigation visible en permanence
    - navigation.tabs.sticky
    # Permet d'afficher la table des matières
    - toc.integrate
    # Permet d'afficher le bouton pour copier le code
    - content.code.copy
    # Permet d'afficher un bouton "Retour en haut de la page"
    - navigation.top
  plugins:
    - search:
        lang: fr

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          # format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true